### ISSUE TITLE
[Model Registry] Flesh out GQL methods

### ISSUE THREAD

**Issue by wetherc** [wetherc/dstk#25]
Separating these out from #2

  - [x] `createModel`
  - [x] `archiveModel`
  - [x] `listModels`
  - [x] `createModelVersion`
  - [x] `publishModelVersion`
  - [x] `archiveModelVersion`
  - [x] `listModelVersions`
  - [x] `createStorageProvider`
  - [x] `editStorageProvider`
  - [x] `deleteStorageProvider`
  - [x] `listStorageProviders`
  - [x] `getStorageProvider`

**Comment by wetherc** [comment]
going to tackle the create/edit/delete storage provider methods in the next couple PRs

**Comment by wetherc** [comment]
@StephenODea54 holler if you want to claim any of these or if you wanted to start in on some of the UI stuff (#27, #28, #29). Otherwise I'll try and knock the rest of these out tomorrow

**Comment by StephenODea54** [comment]
> @StephenODea54 holler if you want to claim any of these or if you wanted to start in on some of the UI stuff (#27, #28, #29). Otherwise I'll try and knock the rest of these out tomorrow

Yeah feel free to take those. Tomorrow I'll start fleshing out what UI will look like.

**Comment by wetherc** [comment]
just as a heads-up, the model version methods are going to be a little slower-coming. They're where things start intersecting with blob storage, so I need to think through what that upload flow should look like and how we want to handle creation and clean-up of presigned URLs, multipart uploads, and all that jazz
