### ISSUE TITLE
[Web] UI for model management

### ISSUE THREAD

**Issue by wetherc** [wetherc/dstk#28]
This should roughly correspond to the [create / archive / edit / list]Models GQL methods

@StephenODea54 - I'll leave this to you to fill out any additonal info

**Comment by StephenODea54** [comment]
Okay, so here is what I'm thinking @wetherc :

- We'll have a Model Registry page accessible from the sidebar. This page will allow us to access all of our models and versions for those models.
- We'll have a breadcrumb menu at the top for easy navigation between models and their versioning
- A quick action button to create models
- Either have a grid of cards or tabular layout to show all of the models.
  - Whatever the UI, it will show important information about the model, such as model name, created dates, last updated timestamps... whatever we feel is good to show here.
  - Each model will have a settings button that will take the user to a settings page where they can perform the gql mutations.
  - Clicking each card (or row in the table) will take you to the model versioning page.


![image](https://github.com/wetherc/dstk/assets/77359138/93c43d18-0d48-4454-b863-9305e3d64184)

**Comment by wetherc** [comment]
All sounds great to me!

I'm personally partial to a tabular layout for models just to make more info available at once on the page versus a larger card layout, but that's just me. It's pretty common to include a list-vs-grid toggle though. E.g., [tcgplayer](https://www.tcgplayer.com/search/magic/ravnica-remastered?view=list&productLineName=magic&setName=ravnica-remastered&page=1)

One thing to consider, thinking ahead a little bit: we might also want to show which models have any active deployments. Obviously the deployments piece we haven't built out yet, but doesn't hurt to start thinking where/how on the models and model versions pages we want to surface that detail and ultimately link out to the actual deployments

**Comment by wetherc** [comment]
Also ref. https://blog.research.google/2020/07/introducing-model-card-toolkit-for.html?m=1 if you haven't seen this before

**Comment by StephenODea54** [comment]
Not a problem! Let's start with the tabular format and possibly revisit later.

Also, I totally agree on showing the deployments. We could throw this in a badge that shows the current status. It could have values such as deployed, not deployed, archived, etc.

Also also, I think we can do some nice ui/ux design stuff on the model versioning page based on that google paper you linked. Maybe something like once a user navigates to a particular model we can show things like the description and the other metadata.

Gonna do my last bit of Christmas shopping today so I'll try to knock out as much of this feature as I can!

**Comment by wetherc** [comment]
Sounds good! I'm proctoring/grading finals today so I probably won't be super responsive till tomorrow/saturday

**Comment by StephenODea54** [comment]
Thoughts on what metadata to include on this view? There are a couple of UI ideas I had for the table, but I'm gonna hold off until we decide on what we want to show on this page in addition to what is shown below (storage provider name, days since last initiation, stage/environment, etc). We could always just circle back to this later since this isn't super important right now.

<img width="767" alt="image" src="https://github.com/wetherc/dstk/assets/77359138/3ae02d76-f68b-47a6-a6fa-068382946af8">

**Comment by wetherc** [comment]
I'm liking it! Nothing else really jumps to mind that I'd add to that screen except maybe the number of versions that have been created? For the deployments column, any thoughts on how we might want to show deployments across multiple model versions thagay all be in different active/pending/failed/archived states? I started noodling on that last night and wasn't coming up with any great ideas

**Comment by StephenODea54** [comment]
Yeah I was thinking about that too. I definitely don't want to have a row per model version (i.e. if Model 1 has three versions then there are three rows), cause I don't want to add too much visual noise. I'm leaning towards having the user click the row which then takes them to a new page where we show more granular details about that specific model (Model cards / descriptions at the top, model versions in another table).

For the extra column, I'm thinking either having a "total versions" column that counts the number of versions (like you mentioned), or a "Latest Version" column that shows the most recent model version.

Excalidraw representation of specific model page:
![image](https://github.com/wetherc/dstk/assets/77359138/b0e2e6dd-a02e-4f00-a7e8-594e1a7e4e0e)

**Comment by wetherc** [comment]
Totally agree that keeping versions and models as separate pages is the way to go.

Total versions and latest version should always be exactly equal since version is an autoincrementing integer, so I think it just comes down to what we want the column header to read. I think just "Versions" is reasonable?

What do you think about, in that Deployments column, having like `Active: 3` / `Failed: 1` / `Pending: 2` badges all in the same table cell to represent divergent states among multiple deployments within a single model? Clicking into the model would bring up the details of each version's deployment, but that might give a good at-a-glance idea of like "are my deployments generally healthy or not". And then if we could have a `None` badge if the model is active but without any deployments, and `Archived` if the model itself has been archived

**Comment by StephenODea54** [comment]
Ah I'm following now! I think that's a great add! I'll incorporate that into the current view.

Today is Hazel's bday (🥹) so probably later this evening I'll get to it.

**Comment by StephenODea54** [comment]
Thoughts? I'm not super concerned with getting the UI perfect right now because we can come back and refine later. 

Also, the bottom pic should have another column for the latest model version. I've had a super busy weekend so I forgot to add that column back in-between doing all of my errands.

<img width="994" alt="image" src="https://github.com/wetherc/dstk/assets/77359138/c0bd76ca-2efb-424b-a072-f6cacf688b3b">

**Comment by wetherc** [comment]
That's awesome! I like the second option a bit more, just condenses all the info a bit, but both look great!

**Comment by StephenODea54** [comment]
That works with me!
