### ISSUE TITLE
[Web] UI for model version management

### ISSUE THREAD

**Issue by wetherc** [wetherc/dstk#29]
This should roughly correspond to the [create / archive / edit / list]ModelVersions GQL methods

@StephenODea54 - I'll leave this to you to fill out any additonal info

**Comment by wetherc** [comment]
I'll get some work on the model version APIs knocked out tomorrow so I'm not blocking you on this

**Comment by StephenODea54** [comment]
Oh no worries you're not blocking on this!

**Comment by StephenODea54** [comment]
Here's what I'm thinking we start with:

<img width="969" alt="image" src="https://github.com/wetherc/dstk/assets/77359138/82472fce-b975-4047-a7c1-c5f1a0635cea">

So very similar to #28 , with the additional of some model cards at the top of the page. We can throw in whatever high level information we want to display.

**Comment by wetherc** [comment]
How do you feel about the cards?

I wonder if it'd be a little cleaner to have a `deployment` column (or similar) in the table with the deployment status of each version, linking out to the actual deployment. If we move that out of the card view, I think we could also nix the latest/last modified cards since that info is all recapitulated elsewhere in the page

**Comment by wetherc** [comment]
I think we also don't need the ability to edit model versions since we want them to inherently have like a write-once-read-many configuration for some guarantees around immutability for auditing purposes and whatnot

**Comment by wetherc** [comment]
Which reminds me I need to update the table in the db to reflect this as well since I just blindly copy pasted from the models table schema

**Comment by StephenODea54** [comment]
I was thinking of using the "status" column to represent the deployment status, so I think we are aligned there. We don't have to use cards at all cause technically all info will be in the table.

Edit: I think if we want to add in the model description that space is probably a good spot for it. But I'm cool with just having a table.

**Comment by StephenODea54** [comment]
> I think we also don't need the ability to edit model versions since we want them to inherently have like a write-once-read-many configuration for some guarantees around immutability for auditing purposes and whatnot

Gotcha, if you want something "edited" it's just a re-deploy (and hence a new version). That makes sense.

**Comment by StephenODea54** [comment]
Edit: Just realized the dates are backwards but you know what I mean

<img width="1020" alt="image" src="https://github.com/wetherc/dstk/assets/77359138/7d197d45-e043-46b3-8711-a970cb55443a">

**Comment by wetherc** [comment]
Love it!

More general question: how do we feel about the UUIDs? Do we want to show them in summary views as the full thing? Do we want to truncate them and just show the first 7 or 8 characters (like git does with commit hashes) and have a "copy to clipboard" button to copy the full ID? Do we hide them completely?

**Comment by StephenODea54** [comment]
Whatever is fine! I threw them in there just in case it was advantageous to the user to be able to access them quickly. If it is, yeah we can truncate and have a copy to clipboard. If you don't think they'll ever need it, we can nix altogether.

**Comment by wetherc** [comment]
I'd say since it's a canonical identifier, we probably should display it in some form, but I'd expect folks to mostly be actually pulling UUIDs by reference in their code rather than hard coding them manually

**Comment by StephenODea54** [comment]
Okay that's cool let's just truncate it then and let them copy/paste it. If we really don't want it we can just remove that column at a later point.
