### ISSUE TITLE
[Web] Add Functionality Features to Model Registry

### ISSUE THREAD

**Issue by StephenODea54** [wetherc/dstk#54]
Server functions to add in:

- [ ] Column Selection
- [ ] Editing
- [ ] Deleting
- [ ] Filtering
- [ ] Creating
- [x] Listing

**Comment by StephenODea54** [comment]
@wetherc 

So the current UI for the model registry table looks like this:

<img width="976" alt="image" src="https://github.com/dstk-labs/dstk/assets/77359138/244e85e2-caa4-461e-8c03-67290f922b7c">


The data fields needed for this are slightly different than the available queries now. Do you care if I make another graphql query that returns these exact fields so I don't have to do groupby aggregations on the frontend? Something like:

```typescript
type LatestMLModelVersion = {
    id: string;
    totalVersions: number; // Just grab the latest version of the model
    deployments // Save for later b/c we haven't touched on this yet.
    createdBy: string;
    modifiedBy: string;
}
```

If not, totally cool.

**Comment by wetherc** [comment]
I think you can get away with just modifying the existing `listModelVersions` query by adding an order by and limit field to it. Just ordering by numeric version descending and pulling back the most recent one will get you all the info that you need, except for the deployment stuff.

Thinking ahead, my gut feel is that we'd want to get deployments for a model version as its own separate query, so I don't know that I'd really want to jam that into this query. But also could be convinced if I'm missing something obvious here

**Comment by StephenODea54** [comment]
Yeah that's fine by me if you're on board.

For the deployment piece, I'll go with whatever you're most comfortable with. Here's kind of where my stance falls on stuff like this: https://www.youtube.com/watch?v=K2ueKlQ2zpk

**Comment by StephenODea54** [comment]
Moving to `dstk-web` repo
