### ISSUE TITLE
[Model Registry] Add listObjectsForModelVersion method

### ISSUE THREAD

**Issue by wetherc** [wetherc/dstk#68]
We're able to successfully upload files associated with a model version, but we also need some way to display them in the UI and elsewhere. We should implement something along the lines of a `listObjectsForModelVersion` query using the [ListObjectsV2Command](https://docs.aws.amazon.com/AmazonS3/latest/userguide/example_s3_ListObjects_section.html).

@StephenODea54 if it's alright with you, I'm going to lob this task your way to just get you a bit more exposure to the S3 stuff. (Plus it'll be relevant for all the frontend work you're focused on right now)

**Comment by StephenODea54** [comment]
Oh yeah that's fine. I've been doing all of the easy stuff anyway 😅

**Comment by StephenODea54** [comment]
Getting started on this tomorrow.
